### ISSUE TITLE
BPS data missing?

### ISSUE THREAD

**Issue by nate-gillman** [LvXinTao/HIMO_dataset#3]
Hi--

Thanks for your work!! :)

I'm trying to train your models, and it seems there is some data missing from the Google drive download? When I run

```bash
 python -m src.train.train_net_2o --exp_name net_2o --num_epochs 1000 --data_dir data
```

I get this error:

```bash
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "Documents/HIMO_dataset/src/train/train_net_2o.py", line 54, in <module>
    main()
  File "Documents/HIMO_dataset/src/train/train_net_2o.py", line 40, in main
    train_dataset=HIMO_2O(args,split='train')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/HIMO_dataset/src/dataset/himo_2o_dataset.py", line 24, in __init__
    self.object_bps=dict(np.load(self.obj_bps_path,allow_pickle=True)) # 1,1024,3
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/himo/lib/python3.11/site-packages/numpy/lib/_npyio_impl.py", line 459, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed_2o/object_bps.npz'
```

It seems that there is a `processed_2o` directory missing from the google drive? Thanks in advance!!

Cheers
Nate

**Comment by LvXinTao** [comment]
Oh! Sorry for the missing files, I missed  the pre-processed data and the instructions of that. I'll add them ASAP.

**Comment by nate-gillman** [comment]
Super, thanks a ton :)

**Comment by Aricling** [comment]
Sorry for the interrupt.  I'd like to ask which SMPL-X model you are using for your dataset representation? Because I saw multiple SMPL-X model versions like SMPL-X v1.1, SMPL-X with removed head bun, and Julia models. I don't know which is the appropriate one... Thanks a lot for the help!

**Comment by LvXinTao** [comment]
> Sorry for the interrupt. I'd like to ask which SMPL-X model you are using for your dataset representation? Because I saw multiple SMPL-X model versions like SMPL-X v1.1, SMPL-X with removed head bun, and Julia models. I don't know which is the appropriate one... Thanks a lot for the help!

We use the SMPL-X v1.1 which contains .npz and .pkl files.

**Comment by Aricling** [comment]
> > Sorry for the interrupt. I'd like to ask which SMPL-X model you are using for your dataset representation? Because I saw multiple SMPL-X model versions like SMPL-X v1.1, SMPL-X with removed head bun, and Julia models. I don't know which is the appropriate one... Thanks a lot for the help!
> 
> We use the SMPL-X v1.1 which contains .npz and .pkl files.

Thank you!

**Comment by chenhh53** [comment]
Hello, it seems that the preprocessed bps files are still missing in the dataset. Could you please provide these files? Or alternatively, could you share the code or instructions on how to generate the bps files?

**Comment by liangxuy** [comment]
The required files are provided.
