### ISSUE TITLE
Missing args.json for pre-trained models

### ISSUE THREAD

**Issue by RammusLeo** [LvXinTao/HIMO_dataset#9]
Hi! I guess the config file of the pre-trained models is not given?
```
$ python eval_himo_2o.py --model_path ./save/net_2o/model000020000.pt --eval_mode wo_mm
Traceback (most recent call last):
  File "eval_himo_2o.py", line 230, in <module>
    val_args,model_args=eval_himo_args()
  File "HIMO_dataset/utils/parser_utils.py", line 453, in eval_himo_args
    model_args=parse_and_load_from_model(val_args)
  File "HIMO_dataset/utils/parser_utils.py", line 11, in parse_and_load_from_model
    assert os.path.exists(args_path), f'args.json not found in {os.path.dirname(model_path)}'
AssertionError: args.json not found in ./save/net_2o
```
Thanks!

**Comment by irem-zeynep** [comment]
Hello, is there any update on this issue?

**Comment by liangxuy** [comment]
We provide the pre-trained models [here](https://drive.google.com/drive/folders/11PYdla0R9GIyYXqDPMle9208Hv8MaUMo?usp=sharing).

**Comment by Liar-zzy** [comment]
> We provide the pre-trained models [here](https://drive.google.com/drive/folders/11PYdla0R9GIyYXqDPMle9208Hv8MaUMo?usp=sharing).

args.json is not provided in this link

**Comment by liangxuy** [comment]
Done. Please rename to `args.json`.

**Comment by Liar-zzy** [comment]
> Done. Please rename to `args.json`.

Hi, after use this command `python -m src.eval.eval_himo_2o`, there are still some wrong in load_model_wo_clip (https://github.com/LvXinTao/HIMO_dataset/blob/c6d6de8f3d94603c9bbacf967d622149c0667958/src/eval/eval_himo_2o.py#L288C5-L288C23).  Is the pre-trained model wrong, or is the net_2o wrong?

**Comment by Hermionee** [comment]
> > Done. Please rename to `args.json`.
> 
> Hi, after use this command `python -m src.eval.eval_himo_2o`, there are still some wrong in load_model_wo_clip (https://github.com/LvXinTao/HIMO_dataset/blob/c6d6de8f3d94603c9bbacf967d622149c0667958/src/eval/eval_himo_2o.py#L288C5-L288C23). Is the pre-trained model wrong, or is the net_2o wrong?

I encountered the same problem. I found that the keys of the model I trained are different from those of the pre-trained model.

**Comment by Liar-zzy** [comment]
> > > Done. Please rename to `args.json`.
> > 
> > 
> > Hi, after use this command `python -m src.eval.eval_himo_2o`, there are still some wrong in load_model_wo_clip (https://github.com/LvXinTao/HIMO_dataset/blob/c6d6de8f3d94603c9bbacf967d622149c0667958/src/eval/eval_himo_2o.py#L288C5-L288C23). Is the pre-trained model wrong, or is the net_2o wrong?
> 
> I encountered the same problem. I found that the keys of the model I trained are different from those of the pre-trained model.

You are right. The released model is not the model in the paper. :joy::joy::joy:

**Comment by Liar-zzy** [comment]
> > > Done. Please rename to `args.json`.
> > 
> > 
> > Hi, after use this command `python -m src.eval.eval_himo_2o`, there are still some wrong in load_model_wo_clip (https://github.com/LvXinTao/HIMO_dataset/blob/c6d6de8f3d94603c9bbacf967d622149c0667958/src/eval/eval_himo_2o.py#L288C5-L288C23). Is the pre-trained model wrong, or is the net_2o wrong?
> 
> I encountered the same problem. I found that the keys of the model I trained are different from those of the pre-trained model.

Hi, have you used the released model?  Can you reproduce the results in the paper?

**Comment by Hermionee** [comment]
> > > > Done. Please rename to `args.json`.
> > > 
> > > 
> > > Hi, after use this command `python -m src.eval.eval_himo_2o`, there are still some wrong in load_model_wo_clip (https://github.com/LvXinTao/HIMO_dataset/blob/c6d6de8f3d94603c9bbacf967d622149c0667958/src/eval/eval_himo_2o.py#L288C5-L288C23). Is the pre-trained model wrong, or is the net_2o wrong?
> > 
> > 
> > I encountered the same problem. I found that the keys of the model I trained are different from those of the pre-trained model.
> 
> Hi, have you used the released model? Can you reproduce the results in the paper?

No, I retrained the model. And the evaluation metrics are not much different, but the visualization results are not ideal.

**Comment by Liar-zzy** [comment]
> > > > > Done. Please rename to `args.json`.
> > > > 
> > > > 
> > > > Hi, after use this command `python -m src.eval.eval_himo_2o`, there are still some wrong in load_model_wo_clip (https://github.com/LvXinTao/HIMO_dataset/blob/c6d6de8f3d94603c9bbacf967d622149c0667958/src/eval/eval_himo_2o.py#L288C5-L288C23). Is the pre-trained model wrong, or is the net_2o wrong?
> > > 
> > > 
> > > I encountered the same problem. I found that the keys of the model I trained are different from those of the pre-trained model.
> > 
> > 
> > Hi, have you used the released model? Can you reproduce the results in the paper?
> 
> No, I retrained the model. And the evaluation metrics are not much different, but the visualization results are not ideal.

Wow, you got the visualization results! Could you help me with it? Thanks! My email is [zyzhang.bbetter@gmail.com](mailto:zyzhang.bbetter@gmail.com)

**Comment by Liar-zzy** [comment]
Hi! where is the HIMO-SegGen? @liangxuy @LvXinTao 
Is there any plan to release it?

**Comment by wangziming0527** [comment]
> Hi! where is the HIMO-SegGen? [@liangxuy](https://github.com/liangxuy) [@LvXinTao](https://github.com/LvXinTao) Is there any plan to release it?

Could you share with me visualization results if you got any? My email is 2743807434@qq.com

**Comment by jyhflash** [comment]
> > > > > > Done. Please rename to `args.json`.
> > > > > 
> > > > > 
> > > > > Hi, after use this command `python -m src.eval.eval_himo_2o`, there are still some wrong in load_model_wo_clip (https://github.com/LvXinTao/HIMO_dataset/blob/c6d6de8f3d94603c9bbacf967d622149c0667958/src/eval/eval_himo_2o.py#L288C5-L288C23). Is the pre-trained model wrong, or is the net_2o wrong?
> > > > 
> > > > 
> > > > I encountered the same problem. I found that the keys of the model I trained are different from those of the pre-trained model.
> > > 
> > > 
> > > Hi, have you used the released model? Can you reproduce the results in the paper?
> > 
> > 
> > No, I retrained the model. And the evaluation metrics are not much different, but the visualization results are not ideal.
> 
> Wow, you got the visualization results! Could you help me with it? Thanks! My email is [zyzhang.bbetter@gmail.com](mailto:zyzhang.bbetter@gmail.com)

Hi, could you share how to visualize with these results? @Liar-zzy @Hermionee , appreciate it. Email: jyhfast@gmail.com
